### ISSUE TITLE
Auto refresh not working

### ISSUE THREAD

**Issue by jeici21** [Zev18/font-randomizer#1]
Hello! I'm the same guy who reviewed your fabulous extension, and I want to warn about my problem with the auto refresh, which seems to happen only to me... It does not work, even when I set it to every half hour and left VSC alone for 2 hours, it does not change the font. I proved to close and reopen VSC to see if only works on startup after that interval, and it didn't work either. I setted 8 fonts on the list and deactivated the activation on startup. I'm doing something wrong? Thanks in advance.

**Comment by Zev18** [comment]
Thank you for letting me know. The auto refresh is supposed to activate even if you don't close vscode. I want to try to recreate your issue on my machine so I can debug it. Can you please let me know:

- What operating system you're using
- If it does nothing, or if it just gives you the notification saying "font changed to __" without changing the font
- If the activate on startup function works
- A screenshot of all fontRandomizer settings you are using

Also, this is unlikely the cause, but just in case, if you have any other extensions that modify the font setting, maybe try disabling those.

Thank you!

**Comment by jeici21** [comment]
1. Windows 11 Home 22H2
2. It does nothing, without notifications.
3. Yes, it works normally, and the manual randomizer works fine too.
4. Here's the screenshot, and I want to ask if the timer continues when VSC is closed... thank you:

![image](https://github.com/Zev18/font-randomizer/assets/114098379/e3f34715-5c9a-4230-8884-aa84d139525c)

**Comment by Zev18** [comment]
Ok, I did some testing. The automatic refresh uses a simple SetInterval() function, just like the random theme switcher extension you seem to have installed, so I'm not sure what could be going wrong here. However, I did notice some things:

1. If you change the setting for the auto refresh, the change only gets put into effect after you open a new window in vscode. So if you change the setting, no matter how long you leave vscode open for, it won't auto refresh until you open a new window.
2. The timer does not run when vscode is closed. So even if you have the auto refresh on, if you don't have activateOnStartup set to true, the font will be the same no matter how long vscode was closed for.

The only thing I can suggest is for you to do is close vscode and open it up again, or do what I did and go to file -> open recent and chose a folder from there. 

I will push an update to the extension that adds a new option for auto refresh, "Every 3 seconds," so that you don't have to wait so long to check if it's working or not. Once that becomes available, try messing with it and see if it works. That's all I can do for now.

**Comment by jeici21** [comment]
Just as you said, the changes only takes effect when a new window is opened! So, it's not an error per se, right? Thank you!
By the way, the Random Theme Switcher extension I use, when it's setted to change themes daily, works in a different way than yours, it changes the theme at 12 a.m regardless of location and only on startup. You could implement that functionality too if you want hahaha... Thanks again!
